#!/bin/sh

TARGET=$(ls ../target/uberjar           \
    | grep $(head -n1 ../project.clj    \
    | cut -d' ' -f3                     \
    | tr -d '"')-standalone)

mkdir -p ansible/files
cp ../target/uberjar/$TARGET ansible/files/zapominalka.jar
cp ../resources/db.json ansible/files
cp ../demo/index.html ansible/files
cd ansible
ansible-playbook -i $@ zapominalka.yml --skip-tags=install
