# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  # The Clojure app is a process running on port 3000 by default
  # (you can customize this)
  # This lets you view the app directly (without nginx in front of it)
  # by visiting localhost:3100
  # config.vm.network :forwarded_port, guest: 3000, host: 3000

  # Use localhost:8000 to connect to nginx
  config.vm.network :forwarded_port, guest: 80, host: 8881
end
